# Generated by Django 2.1.5 on 2019-03-23 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=60)),
                ('headline', models.CharField(max_length=140)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
