# Generated by Django 2.1.5 on 2019-03-27 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=140, null=True)),
                ('source_id', models.CharField(max_length=140)),
                ('source_name', models.CharField(max_length=140)),
                ('title', models.CharField(max_length=140)),
                ('url', models.CharField(max_length=400)),
                ('image_url', models.CharField(max_length=400, null=True)),
                ('content', models.TextField(null=True)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('color', models.CharField(max_length=12)),
            ],
        ),
    ]
